In [10]:
#We first import the pandas library and the provided data
import pandas as pd
import os
sources_list = [file for file in os.listdir('../Sources/3.-Population/') if file.endswith('.csv')]
for file in sources_list:
    globals()[file[:-4]] = pd.read_csv('../Sources/3.-Population/' + file)

In [11]:
#We import external data
external = [file for file in os.listdir('../Sources/External_sources/') if file.endswith('.csv')]
for file in external:
    globals()[file[:-4]] = pd.read_csv('../Sources/External_sources/' + file)

In [12]:
deaths.head()

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,0-4,1
1,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4,1
2,2017,1,Ciutat Vella,3,la Barceloneta,0-4,0
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",0-4,0
4,2017,2,Eixample,5,el Fort Pienc,0-4,0

In [13]:
#Change renta dataset column - Codi Barri to the same on as the all other's data sets "Neighborhood.Code"
_distribucio_territorial_renda_familiar.head()
print(_distribucio_territorial_renda_familiar.columns)
_distribucio_territorial_renda_familiar.rename(columns={"Codi_Barri":"Neighborhood.Code"},inplace=True)

Index(['Any', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'Població', 'Índex RFD Barcelona = 100'],
      dtype='object')

In [14]:
#All datasets share the same variable Neighborhood code
_distribucio_territorial_renda_familiar.Any.value_counts()

2017    73
Name: Any, dtype: int64

In [15]:
#We now keep only the data from 2017:
immigrants_by_nationality_2017 = immigrants_by_nationality[immigrants_by_nationality["Year"] == 2017]
population_2017 = population[population["Year"] == 2017]
deaths_2017 = deaths[deaths["Year"] == 2017]
immigrants_emigrants_by_sex_2017 = immigrants_emigrants_by_sex[immigrants_emigrants_by_sex["Year"] == 2017]
immigrants_emigrants_by_age_2017 = immigrants_emigrants_by_age[immigrants_emigrants_by_age["Year"] == 2017]
births_2017 = births[births["Year"] == 2017]

In [16]:
#We merge deaths with familiar rent
merged=pd.merge(deaths_2017,_distribucio_territorial_renda_familiar[["Índex RFD Barcelona = 100","Població",'Neighborhood.Code']],how="right",on="Neighborhood.Code")
print(merged.columns)
merged.head(30)
#Atorgant a la renda mitjana de Barcelona un valor de 100, els barris de renda molt baixa són el que tenen una renda inferior a 63, els de renda baixa, de 63 a 79, els de renda mitjana-baixa, de 79 a 100, els de renda mitjana-alta, de 100 a 126, els de renda alta de 126 a 159 i els de renda molt alta, superior a 159.

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Índex RFD Barcelona = 100',
       'Població'],
      dtype='object')

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number,Índex RFD Barcelona = 100,Població
0,2017,1,Ciutat Vella,1,el Raval,0-4,1,71.2,47986
1,2017,1,Ciutat Vella,1,el Raval,5-9,0,71.2,47986
2,2017,1,Ciutat Vella,1,el Raval,10-14,0,71.2,47986
3,2017,1,Ciutat Vella,1,el Raval,15-19,0,71.2,47986
4,2017,1,Ciutat Vella,1,el Raval,20-24,0,71.2,47986
5,2017,1,Ciutat Vella,1,el Raval,25-29,1,71.2,47986
6,2017,1,Ciutat Vella,1,el Raval,30-34,2,71.2,47986
7,2017,1,Ciutat Vella,1,el Raval,35-39,2,71.2,47986
8,2017,1,Ciutat Vella,1,el Raval,40-44,9,71.2,47986
9,2017,1,Ciutat Vella,1,el Raval,45-49,14,71.2,47986
10,2017,1,Ciutat Vella,1,el Raval,50-54,12,71.2,47986
11,2017,1,Ciutat Vella,1,el Raval,55-59,11,71.2,47986
12,2017,1,Ciutat Vella,1,el Raval,60-64,16,71.2,47986
13,2017,1,Ciutat Vella,1,el Raval,65-69,25,71.2,47986
14,2017,1,Ciutat Vella,1,el Raval,70-74,21,71.2,47986
15,2017,1,Ciutat Vella,1,el Raval,75-79,32,71.2,47986
16,2017,1,Ciutat Vella,1,el Raval,80-84,68,71.2,47986
17,2017,1,Ciutat Vella,1,el Raval,85-89,52,71.2,47986
18,2017,1,Ciutat Vella,1,el Raval,90-94,57,71.2,47986
19,2017,1,Ciutat Vella,1,el Raval,95-99,17,71.2,47986
20,2017,1,Ciutat Vella,1,el Raval,>=100,6,71.2,47986
21,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4,1,106.1,16240
22,2017,1,Ciutat Vella,2,el Barri Gòtic,5-9,0,106.1,16240
23,2017,1,Ciutat Vella,2,el Barri Gòtic,10-14,0,106.1,16240
24,2017,1,Ciutat Vella,2,el Barri Gòtic,15-19,0,106.1,16240
25,2017,1,Ciutat Vella,2,el Barri Gòtic,20-24,0,106.1,16240
26,2017,1,Ciutat Vella,2,el Barri Gòtic,25-29,0,106.1,16240
27,2017,1,Ciutat Vella,2,el Barri Gòtic,30-34,1,106.1,16240
28,2017,1,Ciutat Vella,2,el Barri Gòtic,35-39,1,106.1,16240
29,2017,1,Ciutat Vella,2,el Barri Gòtic,40-44,0,106.1,16240

In [17]:
#We gropued the ages deatsh csv by interval of 19 instead of 4
rangs = [["0-19","0-4","5-9","10-14","15-19"],["20-39","20-24","25-29","30-34","35-39"],["40-59","40-44","45-49","50-54","55-59"],["60-79","60-64","65-69","70-74","75-79"],["80+","80-84","85-89","90-94","95-99",">=100"]]
deaths_ages_grouped = merged.copy()
for i in range(len(deaths_ages_grouped["Age"])):
    for r in rangs:
        if deaths_ages_grouped["Age"][i] in r:
            deaths_ages_grouped["Age"][i] = r[0]
deaths_ages_grouped.head()

/usr/local/Cellar/jupyterlab/2.1.0/libexec/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number,Índex RFD Barcelona = 100,Població
0,2017,1,Ciutat Vella,1,el Raval,0-19,1,71.2,47986
1,2017,1,Ciutat Vella,1,el Raval,0-19,0,71.2,47986
2,2017,1,Ciutat Vella,1,el Raval,0-19,0,71.2,47986
3,2017,1,Ciutat Vella,1,el Raval,0-19,0,71.2,47986
4,2017,1,Ciutat Vella,1,el Raval,20-39,0,71.2,47986

In [18]:
#Most deaths on 2017 by age, neig and dist
deaths_ages_grouped.groupby(["District.Name","Neighborhood.Name","Age"])[["Number"]].sum().sort_values("Number",ascending = False)

                                                            Number
District.Name  Neighborhood.Name                     Age
Eixample       la Nova Esquerra de l'Eixample        80+       404
               la Dreta de l'Eixample                80+       390
               la Sagrada Família                    80+       382
Gràcia         la Vila de Gràcia                     80+       372
Sant Andreu    Sant Andreu                           80+       340
...                                                            ...
Horta-Guinardó la Clota                              0-19        0
                                                     20-39       0
Nou Barris     la Trinitat Nova                      0-19        0
               Vallbona                              20-39       0
Ciutat Vella   Sant Pere, Santa Caterina i la Ribera 0-19        0

[365 rows x 1 columns]

In [19]:
#Most death by neigh <40
deaths_ages_grouped[(deaths_ages_grouped["Age"] == rangs[0][0]) | (deaths_ages_grouped["Age"] == rangs[1][0])].groupby(["District.Name","Neighborhood.Name","Age"])[["Number"]].sum().sort_values("Number",ascending = False).head(20)

                                                      Number
District.Name  Neighborhood.Name               Age
Ciutat Vella   el Raval                        20-39       5
Sants-Montjuïc la Marina de Port               20-39       5
Nou Barris     Vilapicina i la Torre Llobeta   20-39       4
Les Corts      la Maternitat i Sant Ramon      20-39       4
Eixample       l'Antiga Esquerra de l'Eixample 20-39       4
               la Dreta de l'Eixample          20-39       3
Horta-Guinardó el Carmel                       20-39       3
Sant Martí     el Clot                         20-39       3
Horta-Guinardó Horta                           20-39       3
Sant Martí     la Verneda i la Pau             20-39       3
Gràcia         la Vila de Gràcia               0-19        3
Sant Andreu    la Sagrera                      0-19        3
Les Corts      les Corts                       20-39       3
Nou Barris     la Prosperitat                  20-39       3
Eixample       la Nova Esquerra de l'Eixample  20-39       3
Sant Andreu    el Congrés i els Indians        20-39       3
Eixample       el Fort Pienc                   20-39       3
                                               0-19        3
Nou Barris     el Turó de la Peira             20-39       2
Sants-Montjuïc la Font de la Guatlla           20-39       2

In [20]:
#Apply the same changes for range "Age" to the population dataframe
rangs = [["0-19","0-4","5-9","10-14","15-19"],["20-39","20-24","25-29","30-34","35-39"],["40-59","40-44","45-49","50-54","55-59"],["60-79","60-64","65-69","70-74","75-79"],["80+","80-84","85-89","90-94","95-99",">=100"]]
population_grouped = population_2017.copy()
for i in range(len(population_grouped["Age"])):
    for r in rangs:
        if population_grouped["Age"][i] in r:
            population_grouped["Age"][i] = r[0]

/usr/local/Cellar/jupyterlab/2.1.0/libexec/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [21]:
#Most populated districts from barcelona
population_grouped.groupby(["District.Name","Neighborhood.Name"]).sum()[["Number"]].sort_values("Number",ascending = False).head(25)

                                                        Number
District.Name       Neighborhood.Name
Eixample            la Nova Esquerra de l'Eixample       58180
Sant Andreu         Sant Andreu                          57183
Eixample            la Sagrada Família                   51539
Gràcia              la Vila de Gràcia                    50662
Sarrià-Sant Gervasi Sant Gervasi - Galvany               47666
Ciutat Vella        el Raval                             47608
Les Corts           les Corts                            46009
Eixample            la Dreta de l'Eixample               44052
                    l'Antiga Esquerra de l'Eixample      42284
Sants-Montjuïc      Sants                                41127
                    el Poble Sec                         40228
Eixample            Sant Antoni                          38345
Sant Martí          el Camp de l'Arpa del Clot           38168
Horta-Guinardó      el Guinardó                          36467
Gràcia              el Camp d'en Grassot i Gràcia Nova   34329
Sant Martí          el Poblenou                          33843
Eixample            el Fort Pienc                        32016
Horta-Guinardó      el Carmel                            31551
Sants-Montjuïc      la Marina de Port                    30584
Sarrià-Sant Gervasi el Putxet i el Farró                 29470
Sant Andreu         la Sagrera                           29084
Sant Martí          la Verneda i la Pau                  28691
                    el Clot                              27039
Horta-Guinardó      Horta                                26715
Nou Barris          la Prosperitat                       26389

In [22]:
merged_death_rent = deaths_ages_grouped.copy()
merged_death_rent[(merged_death_rent["Age"] == rangs[0][0]) | (merged_death_rent["Age"] == rangs[1][0])].groupby(["District.Name","Neighborhood.Name","Age","Índex RFD Barcelona = 100"])[["Number"]].sum().sort_values("Number",ascending = False).head(20)

                                                                                Number
District.Name  Neighborhood.Name               Age   Índex RFD Barcelona = 100
Ciutat Vella   el Raval                        20-39 71.2                            5
Sants-Montjuïc la Marina de Port               20-39 69.3                            5
Nou Barris     Vilapicina i la Torre Llobeta   20-39 63.8                            4
Les Corts      la Maternitat i Sant Ramon      20-39 114.2                           4
Eixample       l'Antiga Esquerra de l'Eixample 20-39 137.2                           4
               la Dreta de l'Eixample          20-39 175.9                           3
Horta-Guinardó el Carmel                       20-39 54.2                            3
Sant Martí     el Clot                         20-39 83.6                            3
Horta-Guinardó Horta                           20-39 79.8                            3
Sant Martí     la Verneda i la Pau             20-39 57.0                            3
Gràcia         la Vila de Gràcia               0-19  104.4                           3
Sant Andreu    la Sagrera                      0-19  77.1                            3
Les Corts      les Corts                       20-39 120.0                           3
Nou Barris     la Prosperitat                  20-39 56.0                            3
Eixample       la Nova Esquerra de l'Eixample  20-39 110.2                           3
Sant Andreu    el Congrés i els Indians        20-39 75.1                            3
Eixample       el Fort Pienc                   20-39 106.5                           3
                                               0-19  106.5                           3
Nou Barris     el Turó de la Peira             20-39 51.9                            2
Sants-Montjuïc la Font de la Guatlla           20-39 82.9                            2

In [23]:
vida = _est_salut_publica_esp_vida.copy()
vida2017 = vida[vida.Anys_Periode == '2013-2017']
vida2017

,Anys_Periode,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Nombre
511,2013-2017,1,Ciutat Vella,1,el Raval,81.3
512,2013-2017,1,Ciutat Vella,2,el Barri Gòtic,81.8
513,2013-2017,1,Ciutat Vella,3,la Barceloneta,80.7
514,2013-2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",82.8
515,2013-2017,2,Eixample,5,el Fort Pienc,84.5
...,...,...,...,...,...,...
579,2013-2017,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,85.6
580,2013-2017,10,Sant Martí,70,el Besòs i el Maresme,84.3
581,2013-2017,10,Sant Martí,71,Provençals del Poblenou,85.2
582,2013-2017,10,Sant Martí,72,Sant Martí de Provençals,85.0
583,2013-2017,10,Sant Martí,73,la Verneda i la Pau,84.4

In [24]:
vida2017.drop("Anys_Periode",axis=1,inplace=True)

/usr/local/Cellar/jupyterlab/2.1.0/libexec/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [25]:
vida2017.columns = ['Codi_Districte', 'Nom_Districte', 'Neighborhood.Code', 'Nom_Barri', 'Nombre']
vida2017

,Codi_Districte,Nom_Districte,Neighborhood.Code,Nom_Barri,Nombre
511,1,Ciutat Vella,1,el Raval,81.3
512,1,Ciutat Vella,2,el Barri Gòtic,81.8
513,1,Ciutat Vella,3,la Barceloneta,80.7
514,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",82.8
515,2,Eixample,5,el Fort Pienc,84.5
...,...,...,...,...,...
579,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,85.6
580,10,Sant Martí,70,el Besòs i el Maresme,84.3
581,10,Sant Martí,71,Provençals del Poblenou,85.2
582,10,Sant Martí,72,Sant Martí de Provençals,85.0
583,10,Sant Martí,73,la Verneda i la Pau,84.4

In [26]:
merged_death_rent=pd.merge(merged_death_rent,vida2017[["Neighborhood.Code","Nombre"]],how="left",on="Neighborhood.Code")
print(merged_death_rent.columns)

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Índex RFD Barcelona = 100',
       'Població', 'Nombre'],
      dtype='object')

In [27]:
merged_death_rent.columns

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Índex RFD Barcelona = 100',
       'Població', 'Nombre'],
      dtype='object')

In [28]:
#Eliminate Columns,DON'T RUN AGAIN
#merged_death_rent.drop("Nom_Districte_x",axis=1,inplace=True)
#merged_death_rent.drop("Nom_Barri_x",axis=1,inplace=True)
#merged_death_rent.drop("Nom_Districte_y",axis=1,inplace=True)
#merged_death_rent.drop("Nom_Barri_y",axis=1,inplace=True)
#merged_death_rent.drop("Nombre",axis=1,inplace=True)

In [29]:
#Eliminate Columns,DON'T RUN AGAIN
#merged_death_rent.drop("Codi_Districte",axis=1,inplace=True)

In [30]:
merged_death_rent

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number,Índex RFD Barcelona = 100,Població,Nombre
0,2017,1,Ciutat Vella,1,el Raval,0-19,1,71.2,47986,81.3
1,2017,1,Ciutat Vella,1,el Raval,0-19,0,71.2,47986,81.3
2,2017,1,Ciutat Vella,1,el Raval,0-19,0,71.2,47986,81.3
3,2017,1,Ciutat Vella,1,el Raval,0-19,0,71.2,47986,81.3
4,2017,1,Ciutat Vella,1,el Raval,20-39,0,71.2,47986,81.3
...,...,...,...,...,...,...,...,...,...,...
1528,2017,10,Sant Martí,73,la Verneda i la Pau,80+,66,57.0,28725,84.4
1529,2017,10,Sant Martí,73,la Verneda i la Pau,80+,72,57.0,28725,84.4
1530,2017,10,Sant Martí,73,la Verneda i la Pau,80+,62,57.0,28725,84.4
1531,2017,10,Sant Martí,73,la Verneda i la Pau,80+,16,57.0,28725,84.4
1532,2017,10,Sant Martí,73,la Verneda i la Pau,80+,3,57.0,28725,84.4

In [31]:
danger_data = merged_death_rent.copy()
danger_data.rename(columns = {"Índex RFD Barcelona = 100":"Revenue_Index"},inplace = True)
#We create 4 revenue categories for the negihborhoods based on their revenue levels
danger_data["Category"] = ["Very poor" if e < 63 
                                          else "Poor" if e < 79
                                          else "Low middle class" if e < 100
                                          else "High middle class" if e < 126
                                          else "Rich" if e < 159
                                          else "Very rich"
                                          for e in danger_data["Revenue_Index"]]
danger_data.rename(columns = {'Number':'Number_Deaths','Nombre':'Life_Expectancy'},inplace = True)
danger_data.drop(['Revenue_Index','Year','District.Code','Neighborhood.Code'],axis=1,inplace = True)
danger_data[danger_data["Neighborhood.Name"] == "les Tres Torres"]

,District.Name,Neighborhood.Name,Age,Number_Deaths,Població,Life_Expectancy,Category
483,Sarrià-Sant Gervasi,les Tres Torres,0-19,0,16660,86.0,Very rich
484,Sarrià-Sant Gervasi,les Tres Torres,0-19,0,16660,86.0,Very rich
485,Sarrià-Sant Gervasi,les Tres Torres,0-19,0,16660,86.0,Very rich
486,Sarrià-Sant Gervasi,les Tres Torres,0-19,0,16660,86.0,Very rich
487,Sarrià-Sant Gervasi,les Tres Torres,20-39,0,16660,86.0,Very rich
488,Sarrià-Sant Gervasi,les Tres Torres,20-39,0,16660,86.0,Very rich
489,Sarrià-Sant Gervasi,les Tres Torres,20-39,1,16660,86.0,Very rich
490,Sarrià-Sant Gervasi,les Tres Torres,20-39,0,16660,86.0,Very rich
491,Sarrià-Sant Gervasi,les Tres Torres,40-59,1,16660,86.0,Very rich
492,Sarrià-Sant Gervasi,les Tres Torres,40-59,0,16660,86.0,Very rich
493,Sarrià-Sant Gervasi,les Tres Torres,40-59,0,16660,86.0,Very rich
494,Sarrià-Sant Gervasi,les Tres Torres,40-59,4,16660,86.0,Very rich
495,Sarrià-Sant Gervasi,les Tres Torres,60-79,6,16660,86.0,Very rich
496,Sarrià-Sant Gervasi,les Tres Torres,60-79,5,16660,86.0,Very rich
497,Sarrià-Sant Gervasi,les Tres Torres,60-79,12,16660,86.0,Very rich
498,Sarrià-Sant Gervasi,les Tres Torres,60-79,10,16660,86.0,Very rich
499,Sarrià-Sant Gervasi,les Tres Torres,80+,24,16660,86.0,Very rich
500,Sarrià-Sant Gervasi,les Tres Torres,80+,30,16660,86.0,Very rich
501,Sarrià-Sant Gervasi,les Tres Torres,80+,30,16660,86.0,Very rich
502,Sarrià-Sant Gervasi,les Tres Torres,80+,17,16660,86.0,Very rich
503,Sarrià-Sant Gervasi,les Tres Torres,80+,6,16660,86.0,Very rich

In [32]:
#We group the deaths and population by age group and neighborhood
deaths_by_age = danger_data.groupby(["Neighborhood.Name","Age"],as_index=False).aggregate({'District.Name':'first','Number_Deaths':'sum','Població':'first','Life_Expectancy':'mean','Category':'first'})

In [34]:
#We compute the population and neighborhoods by category:
life_expectancies_refined = deaths_by_age[["Neighborhood.Name","Població","Life_Expectancy","Category"]].groupby(["Neighborhood.Name"],as_index = False).first()
life_expectancies_refined["Neighborhoods"] = 1
summary_table = life_expectancies_refined.groupby("Category")["Població","Neighborhoods"].sum()
summary_table["% of population"] = summary_table["Població"] / summary_table["Població"].sum()
summary_table["% of population"] = pd.Series(["{0:.2f}%".format(val*100) for val in summary_table["% of population"]],index = summary_table.index)
summary_table.rename(columns = {"Població":"Population"},inplace=True)
summary_table

/usr/local/Cellar/jupyterlab/2.1.0/libexec/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  after removing the cwd from sys.path.

                   Population  Neighborhoods % of population
Category
High middle class      416741             13          25.64%
Low middle class       443565             22          27.29%
Poor                   282609             11          17.39%
Rich                    90528              4           5.57%
Very poor              210499             16          12.95%
Very rich              181195              7          11.15%

In [35]:
#We compute a more precise life expectancy by category
life_expectancies_refined["Ponderated_pop"] = life_expectancies_refined["Població"] * life_expectancies_refined["Life_Expectancy"]
life_exp = life_expectancies_refined.groupby("Category")[["Població","Ponderated_pop"]].sum()
life_exp["Life Expectancy"] = round(life_exp["Ponderated_pop"]/life_exp["Població"],2)
life_exp.drop(['Població','Ponderated_pop'],axis=1,inplace=True)
life_exp.sort_values(by = 'Life Expectancy',ascending = False)

                   Life Expectancy
Category
Rich                         85.00
High middle class            84.94
Low middle class             84.33
Poor                         83.44
Very poor                    81.44
Very rich                    80.73

In [36]:
##deaths_grouped = danger_by_ages.groupby(["Category","Age"])[["Nº Deaths","Population"]].sum()
##deaths_grouped["Death ratio"] = deaths_grouped["Nº Deaths"] / deaths_grouped["Population"]
##deaths_grouped['Death ratio'] = pd.Series(["{0:.2f}%".format(val * 100) for val in deaths_grouped['Death ratio']], index = deaths_grouped.index)
##deaths_grouped.sort_values(by = "Death ratio",inplace = True)
##deaths_grouped
deaths_by_age

,Neighborhood.Name,Age,District.Name,Number_Deaths,Població,Life_Expectancy,Category
0,Baró de Viver,0-19,Sant Andreu,0,2539,NaN,Poor
1,Baró de Viver,20-39,Sant Andreu,1,2539,NaN,Poor
2,Baró de Viver,40-59,Sant Andreu,3,2539,NaN,Poor
3,Baró de Viver,60-79,Sant Andreu,7,2539,NaN,Poor
4,Baró de Viver,80+,Sant Andreu,11,2539,NaN,Poor
...,...,...,...,...,...,...,...
360,les Tres Torres,0-19,Sarrià-Sant Gervasi,0,16660,86.0,Very rich
361,les Tres Torres,20-39,Sarrià-Sant Gervasi,1,16660,86.0,Very rich
362,les Tres Torres,40-59,Sarrià-Sant Gervasi,5,16660,86.0,Very rich
363,les Tres Torres,60-79,Sarrià-Sant Gervasi,33,16660,86.0,Very rich
364,les Tres Torres,80+,Sarrià-Sant Gervasi,107,16660,86.0,Very rich

In [39]:
#We finally compute the death ratio by category and age group:
population_grouped_2 = population_grouped.groupby(['Neighborhood.Name','Age'],as_index = False)['Number'].sum()
merged_pop = deaths_by_age.merge(population_grouped_2,how = 'left',on = ['Neighborhood.Name','Age'])
merged_pop.drop("Població",axis=1,inplace=True)
merged_pop.rename(columns = {'Number':'Population'},inplace=True)
merged_pop_grouped = merged_pop.groupby(['Category','Age'])[['Number_Deaths','Population']].sum()
merged_pop_grouped["Death ratio"] = merged_pop_grouped["Number_Deaths"] / merged_pop_grouped["Population"]
merged_pop_grouped.drop(['Population'],axis=1,inplace=True)
merged_pop_grouped['Death ratio'] = pd.Series(["{0:.2f}%".format(val * 100) for val in merged_pop_grouped['Death ratio']], index = merged_pop_grouped.index)
merged_pop_grouped = merged_pop_grouped.unstack()
merged_pop_grouped

                  Number_Deaths                         Death ratio         \
Age                        0-19 20-39 40-59 60-79   80+        0-19  20-39
Category
High middle class            14    26   219   943  2781       0.02%  0.02%
Low middle class             12    27   265  1093  2951       0.02%  0.02%
Poor                          8    21   194   734  1695       0.02%  0.03%
Rich                          2     4    37   170   590       0.01%  0.02%
Very poor                     7    18   173   557  1293       0.02%  0.03%
Very rich                     3     9    71   363  1284       0.01%  0.02%


Age                40-59  60-79    80+
Category
High middle class  0.19%  1.13%  8.88%
Low middle class   0.20%  1.29%  9.06%
Poor               0.23%  1.36%  8.56%
Rich               0.14%  1.04%  9.74%
Very poor          0.28%  1.33%  8.00%
Very rich          0.14%  1.07%  9.35%

In [44]:
with pd.ExcelWriter("../Results.xls", engine="openpyxl", mode="a") as writer: 
    life_exp.to_excel(writer, sheet_name='Life expectancies')
    merged_pop_grouped.to_excel(writer, sheet_name='Death ratio by revenue')

InvalidFileException: openpyxl does not support the old .xls file format, please use xlrd to read this file, or convert it to the more recent .xlsx file format.