In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
full_csv = pd.read_csv("datasets/1.-Transportation/accidents-2017.csv")
full_csv

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
2,2017S010210,Unknown,Unknown,Litoral (Besòs) ...,Friday,December,8,21,Afternoon,5,0,5,2,2.167356,41.360885
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [21]:
difference = 10339 - len_total
difference

9983

In [20]:
len_total = len1 + len2 + len3 + len4 + len5 + len6 + len7 + len8
len_total

356

In [4]:
len1 = len(full_csv[(full_csv["Month"] == "June") & (full_csv["Day"].isin([23, 24]))])
len1

38

In [5]:
#San Juan Deleted
first_update = full_csv.drop(full_csv[(full_csv["Month"] == "June") & (full_csv["Day"].isin([23, 24]))].index)
first_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
2,2017S010210,Unknown,Unknown,Litoral (Besòs) ...,Friday,December,8,21,Afternoon,5,0,5,2,2.167356,41.360885
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [6]:
len2 = len(first_update[(first_update["Month"] == "September") & (first_update["Day"].isin([22, 23, 24, 25]))])
len2

95

In [7]:
#Merce Deleted
second_update = first_update.drop(first_update[(first_update["Month"] == "September") & (first_update["Day"].isin([22, 23, 24, 25]))].index)
second_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
2,2017S010210,Unknown,Unknown,Litoral (Besòs) ...,Friday,December,8,21,Afternoon,5,0,5,2,2.167356,41.360885
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [8]:
len3 = len(second_update[(second_update["Month"] == "December") & (second_update["Day"].isin([24, 25]))])
len3

30

In [9]:
#Christmas Deleted
third_update = second_update.drop(second_update[(second_update["Month"] == "December") & (second_update["Day"].isin([24, 25]))].index)
third_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
2,2017S010210,Unknown,Unknown,Litoral (Besòs) ...,Friday,December,8,21,Afternoon,5,0,5,2,2.167356,41.360885
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [10]:
len4 = len(third_update[(third_update["Month"] == "December") & (third_update["Day"].isin([6, 7, 8]))])
len4

35

In [11]:
#December holiday 6-8 Deleted
fourth_update = third_update.drop(third_update[(third_update["Month"] == "December") & (third_update["Day"].isin([6, 7, 8]))].index)
fourth_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [12]:
len5 = len(fourth_update[(fourth_update["Month"] == "April") & (fourth_update["Day"].isin([14, 15, 16, 17]))])
len5

60

In [13]:
#Holy Week Deleted
fifth_update = fourth_update.drop(fourth_update[(fourth_update["Month"] == "April") & (fourth_update["Day"].isin([14, 15, 16, 17]))].index)
fifth_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [14]:
len6 = len(fifth_update[(fifth_update["Month"] == "September") & (fifth_update["Day"].isin([8, 9, 10, 11]))])
len6

69

In [15]:
#Day of Catalonia
sixth_update = fifth_update.drop(fifth_update[(fifth_update["Month"] == "September") & (fifth_update["Day"].isin([8, 9, 10, 11]))].index)
sixth_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [16]:
len7 = len(sixth_update[(sixth_update["Month"] == "December") & (sixth_update["Day"].isin([31]))])
len7

7

In [17]:
#NYE Deleted
sevent_update = sixth_update.drop(sixth_update[(sixth_update["Month"] == "December") & (sixth_update["Day"].isin([31]))].index)
sevent_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [18]:
len8 = len(sevent_update[(sevent_update["Month"] == "January") & (sevent_update["Day"].isin([1]))])
len8

22

In [19]:
#NY Deleted
eight_update = sevent_update.drop(sevent_update[(sevent_update["Month"] == "January") & (sevent_update["Day"].isin([1]))].index)
eight_update

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [25]:
new_update = eight_update
new_update
len(new_update)

9983

In [27]:
#3King Deleted
new_update1 = new_update.drop(new_update[(new_update["Month"] == "January") & (new_update["Day"].isin([6, 7]))].index)
len(new_update1)

9948

In [28]:
#1stMay LW. Part1
new_update2 = new_update1.drop(new_update1[(new_update1["Month"] == "April") & (new_update1["Day"].isin([28, 29, 30]))].index)
len(new_update2)

9878

In [29]:
#1stMay LW. Part2
new_update3 = new_update2.drop(new_update2[(new_update2["Month"] == "May") & (new_update2["Day"].isin([1]))].index)
len(new_update3)

9865

In [30]:
#2nd Monday of Easter
new_update4 = new_update3.drop(new_update3[(new_update3["Month"] == "June") & (new_update3["Day"].isin([2, 3, 4, 5]))].index)
len(new_update4)

9771

In [31]:
#15th August
new_update5 = new_update4.drop(new_update4[(new_update4["Month"] == "August") & (new_update4["Day"].isin([15]))].index)
len(new_update5)

9758

In [32]:
#12th October
new_update6 = new_update5.drop(new_update5[(new_update5["Month"] == "October") & (new_update5["Day"].isin([12]))].index)
len(new_update6)

9741

In [33]:
#1th November
new_update7 = new_update6.drop(new_update6[(new_update6["Month"] == "November") & (new_update6["Day"].isin([1]))].index)
len(new_update7)

9731

In [34]:
#St Esteve
new_update8 = new_update7.drop(new_update7[(new_update7["Month"] == "December") & (new_update7["Day"].isin([26]))].index)
len(new_update8)

9707

In [35]:
#St Jordi
new_update9 = new_update8.drop(new_update8[(new_update8["Month"] == "April") & (new_update8["Day"].isin([23]))].index)
len(new_update9)

9691

In [36]:
#St Valentines
new_update10 = new_update9.drop(new_update9[(new_update9["Month"] == "February") & (new_update9["Day"].isin([14]))].index)
len(new_update10)

9651

In [37]:
file_updated = new_update10

In [38]:
file_updated

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
0,2017S008429,Unknown,Unknown,Número 27 ...,Friday,October,13,8,Morning,2,0,2,2,2.125624,41.340045
1,2017S007316,Unknown,Unknown,Número 3 Zona Franca / Número 50 Zona Franca ...,Friday,September,1,13,Morning,2,0,2,2,2.120452,41.339426
3,2017S006364,Unknown,Unknown,Número 3 Zona Franca ...,Friday,July,21,2,Night,1,0,1,2,2.124529,41.337668
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [39]:
file_updated.drop(["Id", "Neighborhood Name", "Street", "Hour", "Longitude", "Latitude"], axis=1, inplace=True)

In [42]:
file_updated

,District Name,Weekday,Month,Day,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved
0,Unknown,Friday,October,13,Morning,2,0,2,2
1,Unknown,Friday,September,1,Morning,2,0,2,2
3,Unknown,Friday,July,21,Night,1,0,1,2
4,Sant Martí,Thursday,May,25,Afternoon,1,0,1,3
5,Sant Martí,Wednesday,September,20,Morning,1,0,1,2
...,...,...,...,...,...,...,...,...,...
10334,Sant Andreu,Tuesday,April,25,Morning,1,0,1,3
10335,Sant Andreu,Wednesday,March,8,Morning,1,0,1,2
10336,Sant Andreu,Thursday,December,28,Morning,1,0,1,2
10337,Sant Andreu,Friday,July,14,Afternoon,1,0,1,2
10338,Sant Andreu,Sunday,January,8,Afternoon,0,0,0,1

In [28]:
file_updated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9983 entries, 0 to 10338
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   District Name      9983 non-null   object
 1   Weekday            9983 non-null   object
 2   Month              9983 non-null   object
 3   Day                9983 non-null   int64
 4   Part of the day    9983 non-null   object
 5   Mild injuries      9983 non-null   int64
 6   Serious injuries   9983 non-null   int64
 7   Victims            9983 non-null   int64
 8   Vehicles involved  9983 non-null   int64
dtypes: int64(5), object(4)
memory usage: 779.9+ KB

In [29]:
august = file_updated[file_updated["Month"] == "August"]

In [30]:
august

,District Name,Weekday,Month,Day,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved
30,Sant Martí,Thursday,August,31,Afternoon,0,1,1,1
31,Sant Martí,Tuesday,August,15,Afternoon,1,0,1,2
34,Sant Martí,Thursday,August,31,Morning,2,0,2,3
39,Sant Martí,Tuesday,August,1,Afternoon,1,0,1,2
57,Sant Martí,Tuesday,August,8,Night,1,0,1,2
...,...,...,...,...,...,...,...,...,...
10243,Nou Barris,Tuesday,August,8,Afternoon,1,0,1,2
10264,Sant Andreu,Thursday,August,31,Morning,1,0,1,2
10278,Sant Andreu,Sunday,August,27,Morning,2,0,2,1
10288,Sant Andreu,Monday,August,7,Afternoon,1,0,1,2
10311,Sant Andreu,Monday,August,14,Afternoon,1,0,1,2

In [32]:
file_updated["Month"].value_counts()

November     991
May          963
March        935
October      928
July         918
June         870
February     824
January      822
April        785
December     690
August       652
September    605
Name: Month, dtype: int64

In [41]:
file_updated.to_csv("datasets/1.-Transportation/accidents-without-holidays_final_version.csv")