In [54]:
import pandas as pd
import numpy as np

In [55]:
#Importing the Data sets of public transportation in Barcelona
bus_stops = pd.read_csv("../datasets/1.-Transportation/bus-stops.csv",index_col = 0)
public_stops = pd.read_csv("../datasets/1.-Transportation/public-transport.csv", index_col = 0)

In [56]:
#Printing first rows to check if the columns are equal 
print(bus_stops.head())

         Transport  Longitude   Latitude    Bus.Stop        District.Name  \
Code
K014  Day bus stop   2.171619  41.413744  BUS -192--       Horta-Guinardó
K014  Day bus stop   2.134902  41.420222  BUS -124--               Gràcia
K014  Day bus stop   2.162913  41.423187  BUS -117--       Horta-Guinardó
K014  Day bus stop   2.163667  41.422899  BUS -117--       Horta-Guinardó
K014  Day bus stop   2.120212  41.397209  BUS -130--  Sarrià-Sant Gervasi

              Neighborhood.Name
Code
K014                el Guinardó
K014  Vallcarca i els Penitents
K014       la Font d'en Fargues
K014       la Font d'en Fargues
K014                     Sarrià

In [57]:
#Printing first rows to check if the columns are equal 
print(public_stops.head())

        Transport  Longitude   Latitude  \
Code
K001  Underground   2.119370  41.399203
K001  Underground   2.135427  41.397791
K001  Underground   2.185391  41.451492
K001  Underground   2.174473  41.460889
K001  Underground   2.168588  41.387200

                                                Station        District.Name  \
Code
K001  FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...  Sarrià-Sant Gervasi
K001                            FGC (L6) - LA BONANOVA-  Sarrià-Sant Gervasi
K001      METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-           Nou Barris
K001    METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-           Nou Barris
K001         METRO (L1) - CATALUNYA (Rda. Universitat)-             Eixample

           Neighborhood.Name
Code
K001                  Sarrià
K001  Sant Gervasi - Galvany
K001        la Trinitat Nova
K001        Ciutat Meridiana
K001  la Dreta de l'Eixample

In [58]:
#Changing the title and creating the DataFrame of Bus.Stop column to Station to have it equal in both datasets
bus_stops = bus_stops.rename(columns = {"Bus.Stop":"Station"})
bus_stops.head()

,Transport,Longitude,Latitude,Station,District.Name,Neighborhood.Name
Code,,,,,,
K014,Day bus stop,2.171619,41.413744,BUS -192--,Horta-Guinardó,el Guinardó
K014,Day bus stop,2.134902,41.420222,BUS -124--,Gràcia,Vallcarca i els Penitents
K014,Day bus stop,2.162913,41.423187,BUS -117--,Horta-Guinardó,la Font d'en Fargues
K014,Day bus stop,2.163667,41.422899,BUS -117--,Horta-Guinardó,la Font d'en Fargues
K014,Day bus stop,2.120212,41.397209,BUS -130--,Sarrià-Sant Gervasi,Sarrià

In [59]:
#By typing info into the dataframes we can understand data types and how many null values we have
bus_stops.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3162 entries, K014 to K015
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Transport          3162 non-null   object
 1   Longitude          3162 non-null   float64
 2   Latitude           3162 non-null   float64
 3   Station            3162 non-null   object
 4   District.Name      3146 non-null   object
 5   Neighborhood.Name  3146 non-null   object
dtypes: float64(2), object(4)
memory usage: 111.2+ KB

In [60]:
#There are some null values on the neighborhoods that we need to figure out why. 
public_stops.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651 entries, K001 to K001
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Transport          651 non-null    object
 1   Longitude          651 non-null    float64
 2   Latitude           651 non-null    float64
 3   Station            651 non-null    object
 4   District.Name      487 non-null    object
 5   Neighborhood.Name  487 non-null    object
dtypes: float64(2), object(4)
memory usage: 22.9+ KB

In [61]:
#Merging both Data Frames together to have a full data set with all the information about the different public transportations stops in Barcelona
bcn_stops = public_stops.append(bus_stops)

In [62]:
bcn_stops

,Transport,Longitude,Latitude,Station,District.Name,Neighborhood.Name
Code,,,,,,
K001,Underground,2.119370,41.399203,FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...,Sarrià-Sant Gervasi,Sarrià
K001,Underground,2.135427,41.397791,FGC (L6) - LA BONANOVA-,Sarrià-Sant Gervasi,Sant Gervasi - Galvany
K001,Underground,2.185391,41.451492,METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-,Nou Barris,la Trinitat Nova
K001,Underground,2.174473,41.460889,METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-,Nou Barris,Ciutat Meridiana
K001,Underground,2.168588,41.387200,METRO (L1) - CATALUNYA (Rda. Universitat)-,Eixample,la Dreta de l'Eixample
...,...,...,...,...,...,...
K014,Day bus stop,2.183887,41.422024,BUS -191--,Sant Andreu,el Congrés i els Indians
K014,Day bus stop,2.176710,41.446419,BUS -127-81--,Nou Barris,les Roquetes
K015,Night bus stop,2.144596,41.411446,NITBUS -N4--,Gràcia,Vallcarca i els Penitents
K014,Day bus stop,2.142256,41.371176,BUS -91-115-V5--,Sants-Montjuïc,la Bordeta
K015,Night bus stop,2.134932,41.398495,NITBUS -N7--,Sarrià-Sant Gervasi,Sant Gervasi - Galvany

In [63]:
#Calculating the number of Neighborhoods
bcn_stops["Neighborhood.Name"].value_counts()
#There are 73 different neighborhoods.

la Dreta de l'Eixample                   198
el Poble-sec                             131
la Marina del Prat Vermell               126
Vallvidrera, el Tibidabo i les Planes    122
l'Antiga Esquerra de l'Eixample           96
                                        ...
Verdun                                    13
Baró de Viver                              8
la Font de la Guatlla                      7
la Clota                                   5
Can Peguera                                4
Name: Neighborhood.Name, Length: 73, dtype: int64

In [64]:
#Checking if there are any duplicates
bcn_stops[bcn_stops.Station.duplicated()]
#There are around 1500 rows that are duplicates, that demonstrates that some stations have different transports

,Transport,Longitude,Latitude,Station,District.Name,Neighborhood.Name
Code,,,,,,
K001,Underground,2.148557,41.435325,METRO (L3) - MUNDET (Can Marcet)-,Horta-Guinardó,la Vall d'Hebron
K001,Underground,2.084164,41.363278,METRO (L5) - SANT ILDEFONS-,NaN,NaN
K001,Underground,2.072404,41.356151,METRO (L5) - CORNELLÀ CENTRE-,NaN,NaN
K001,Underground,2.208350,41.451604,METRO (L1) - SANTA COLOMA-,NaN,NaN
K001,Underground,2.110976,41.351991,METRO (L1) - BELLVITGE-,NaN,NaN
...,...,...,...,...,...,...
K014,Day bus stop,2.183887,41.422024,BUS -191--,Sant Andreu,el Congrés i els Indians
K014,Day bus stop,2.176710,41.446419,BUS -127-81--,Nou Barris,les Roquetes
K015,Night bus stop,2.144596,41.411446,NITBUS -N4--,Gràcia,Vallcarca i els Penitents
K014,Day bus stop,2.142256,41.371176,BUS -91-115-V5--,Sants-Montjuïc,la Bordeta
K015,Night bus stop,2.134932,41.398495,NITBUS -N7--,Sarrià-Sant Gervasi,Sant Gervasi - Galvany

In [65]:
#Saving the Dataframe to a csv 
bcn_stops.to_csv("../datasets/1.-Transportation/bcn_stops.csv")

In [66]:
bcn_stops

,Transport,Longitude,Latitude,Station,District.Name,Neighborhood.Name
Code,,,,,,
K001,Underground,2.119370,41.399203,FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...,Sarrià-Sant Gervasi,Sarrià
K001,Underground,2.135427,41.397791,FGC (L6) - LA BONANOVA-,Sarrià-Sant Gervasi,Sant Gervasi - Galvany
K001,Underground,2.185391,41.451492,METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-,Nou Barris,la Trinitat Nova
K001,Underground,2.174473,41.460889,METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-,Nou Barris,Ciutat Meridiana
K001,Underground,2.168588,41.387200,METRO (L1) - CATALUNYA (Rda. Universitat)-,Eixample,la Dreta de l'Eixample
...,...,...,...,...,...,...
K014,Day bus stop,2.183887,41.422024,BUS -191--,Sant Andreu,el Congrés i els Indians
K014,Day bus stop,2.176710,41.446419,BUS -127-81--,Nou Barris,les Roquetes
K015,Night bus stop,2.144596,41.411446,NITBUS -N4--,Gràcia,Vallcarca i els Penitents
K014,Day bus stop,2.142256,41.371176,BUS -91-115-V5--,Sants-Montjuïc,la Bordeta
K015,Night bus stop,2.134932,41.398495,NITBUS -N7--,Sarrià-Sant Gervasi,Sant Gervasi - Galvany

In [67]:
bcn_stops["Neighborhood.Name"].isnull()
external_stops=bcn_stops.loc[bcn_stops['Neighborhood.Name'].isnull()]
external_stops #External stops are from outside Barcelona!

,Transport,Longitude,Latitude,Station,District.Name,Neighborhood.Name
Code,,,,,,
K001,Underground,2.083994,41.362753,METRO (L5) - SANT ILDEFONS-,NaN,NaN
K001,Underground,2.100302,41.362977,METRO (L1) - RAMBLA JUST OLIVERAS-,NaN,NaN
K011,Tram,2.098896,41.376486,"TRAMVIA (T1,T2,T3) - CA N'OLIVERES-",NaN,NaN
K011,Tram,2.106023,41.376071,"TRAMVIA (T1,T2,T3) - CAN RIGAL-",NaN,NaN
K011,Tram,2.222916,41.430456,TRAMVIA (T5) - ENCANTS DE SANT ADRIÀ-,NaN,NaN
...,...,...,...,...,...,...
K014,Day bus stop,2.120534,41.425856,BUS -111--,NaN,NaN
K015,Night bus stop,2.055835,41.365599,NITBUS -N15--,NaN,NaN
K014,Day bus stop,2.221753,41.413193,BUS -H16-V33--,NaN,NaN
K014,Day bus stop,2.095815,41.433073,BUS -128--,NaN,NaN
K014,Day bus stop,2.217777,41.418108,BUS -V33--,NaN,NaN

In [68]:
#We are editing the data frame we had by selecting only the rows that are not null in the neighborhood column
bcn_stops=bcn_stops.loc[bcn_stops['Neighborhood.Name'].notna()]
bcn_stops

,Transport,Longitude,Latitude,Station,District.Name,Neighborhood.Name
Code,,,,,,
K001,Underground,2.119370,41.399203,FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...,Sarrià-Sant Gervasi,Sarrià
K001,Underground,2.135427,41.397791,FGC (L6) - LA BONANOVA-,Sarrià-Sant Gervasi,Sant Gervasi - Galvany
K001,Underground,2.185391,41.451492,METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-,Nou Barris,la Trinitat Nova
K001,Underground,2.174473,41.460889,METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-,Nou Barris,Ciutat Meridiana
K001,Underground,2.168588,41.387200,METRO (L1) - CATALUNYA (Rda. Universitat)-,Eixample,la Dreta de l'Eixample
...,...,...,...,...,...,...
K014,Day bus stop,2.183887,41.422024,BUS -191--,Sant Andreu,el Congrés i els Indians
K014,Day bus stop,2.176710,41.446419,BUS -127-81--,Nou Barris,les Roquetes
K015,Night bus stop,2.144596,41.411446,NITBUS -N4--,Gràcia,Vallcarca i els Penitents
K014,Day bus stop,2.142256,41.371176,BUS -91-115-V5--,Sants-Montjuïc,la Bordeta
K015,Night bus stop,2.134932,41.398495,NITBUS -N7--,Sarrià-Sant Gervasi,Sant Gervasi - Galvany

In [69]:
#Now we are creating a new data frame that has the number of stops by neighborhood
stops_per_district=bcn_stops["District.Name"].value_counts().rename_axis('district').reset_index(name='stops')
stops_per_district

              district  stops
0             Eixample    525
1  Sarrià-Sant Gervasi    505
2       Sants-Montjuïc    468
3           Sant Martí    426
4       Horta-Guinardó    420
5           Nou Barris    369
6          Sant Andreu    268
7            Les Corts    231
8               Gràcia    227
9         Ciutat Vella    194

In [70]:
#Importing the Data Frame that includes information about air quality
pollution=pd.read_csv("../datasets/2.-Urban-Environment/air_quality_2018_project2.csv", index_col="Unnamed: 0")
pollution.head()

,nom_cabina,qualitat_aire,codi_dtes,zqa,codi_eoi,longitud,latitud,hora_o3,qualitat_o3,valor_o3,hora_no2,qualitat_no2,valor_no2,hora_pm10,qualitat_pm10,valor_pm10,generat,dateTime
0,Barcelona - Sants,--,ID,1,8019042,2.1331,41.3788,NaN,NaN,NaN,7h,--,--,NaN,NaN,NaN,11/06/2018 9:00,1528700703
1,Barcelona - Eixample,Bona,IH,1,8019043,2.1538,41.3853,8h,Bona,37 µg/m³,8h,Bona,62 µg/m³,9h,Bona,26 µg/m³,11/06/2018 9:00,1528700703
2,Barcelona - Gràcia,Bona,IJ,1,8019044,2.1534,41.3987,8h,Bona,51 µg/m³,8h,Bona,44 µg/m³,9h,Bona,23 µg/m³,11/06/2018 9:00,1528700703
3,Barcelona - Ciutadella,Bona,IL,1,8019050,2.1874,41.3864,8h,Bona,27 µg/m³,8h,Bona,40 µg/m³,NaN,NaN,NaN,11/06/2018 9:00,1528700703
4,Barcelona - Vall Hebron,Bona,IN,1,8019054,2.1480,41.4261,8h,Bona,22 µg/m³,8h,Bona,54 µg/m³,9h,Bona,18 µg/m³,11/06/2018 9:00,1528700703

In [71]:
#Cleaning the pollution dataset. We are taking the Barcelona - info from the neighborhoods to have it in the same format as the info about neighborhoods in our public transportation dataframe
#Taking the unit from the numerical columns to make then a int datatype instead of an object datatype
pollution["nom_cabina"]=pollution["nom_cabina"].str.replace(".*(- )","")
pollution["valor_o3"]=pollution["valor_o3"].str.replace(" µg/m³","")
pollution["valor_no2"]=pollution["valor_no2"].str.replace(" µg/m³","")
pollution["valor_pm10"]=pollution["valor_pm10"].str.replace(" µg/m³","")
# test transformed data
pollution.columns

Index(['nom_cabina', 'qualitat_aire', 'codi_dtes', 'zqa', 'codi_eoi',
       'longitud', 'latitud', 'hora_o3', 'qualitat_o3', 'valor_o3', 'hora_no2',
       'qualitat_no2', 'valor_no2', 'hora_pm10', 'qualitat_pm10', 'valor_pm10',
       'generat', 'dateTime'],
      dtype='object')

In [72]:
#Deleting columns that are not needed for our statistycal analysis
pollution1=pollution.drop(columns=["codi_dtes", "zqa","codi_eoi", "longitud", "latitud", "hora_o3", "hora_pm10", "hora_no2", "qualitat_o3", "qualitat_pm10", "qualitat_no2", "dateTime"])
#Printint the different air stations
print(pollution1["nom_cabina"].value_counts())
#Printing the unique names of the neighborhoods
neighborhood_list=list(bcn_stops["Neighborhood.Name"].unique())
district_list=list(bcn_stops["District.Name"].unique())
#Printing the unique names of the Districts 
print(district_list)

Eixample        4582
Gràcia          4582
Poblenou        4582
Palau Reial     4582
Ciutadella      4582
Sants           4582
Vall Hebron     4582
Observ Fabra    3909
Name: nom_cabina, dtype: int64
['Sarrià-Sant Gervasi', 'Nou Barris', 'Eixample', 'Horta-Guinardó', 'Sants-Montjuïc', 'Sant Martí', 'Les Corts', 'Sant Andreu', 'Gràcia', 'Ciutat Vella']

In [73]:
#Grouping all the neighborhoods by district to have a better understanding
    #on how the air stations and districts are related
bcn_stops.groupby("District.Name")["Neighborhood.Name"].value_counts()

District.Name        Neighborhood.Name
Ciutat Vella         el Raval                                 56
                     la Barceloneta                           50
                     Sant Pere, Santa Caterina i la Ribera    44
                     el Barri Gòtic                           43
                     la Marina del Prat Vermell                1
                                                              ..
Sarrià-Sant Gervasi  Sant Gervasi - la Bonanova               95
                     Sant Gervasi - Galvany                   94
                     Sarrià                                   90
                     el Putxet i el Farró                     65
                     les Tres Torres                          39
Name: Neighborhood.Name, Length: 74, dtype: int64

In [74]:
bcn_stops["District.Name"].value_counts()

Eixample               525
Sarrià-Sant Gervasi    505
Sants-Montjuïc         468
Sant Martí             426
Horta-Guinardó         420
Nou Barris             369
Sant Andreu            268
Les Corts              231
Gràcia                 227
Ciutat Vella           194
Name: District.Name, dtype: int64

In [75]:
#We have each Air Station to a different district

#Gràcia corresponds to Gràcia
#Ciutadella corresponds to Poblenou
#Sants corresponds to Sants-Montjuïc
#Vall Hebron corresponds to Horta-Guinardó
#Poblenou corresponds to Sant Martí
#Eixample corresponds to Eixample
#Observ Fabra corresponds to Sarrià-Sant Gervasi

In [76]:
bcn_stops.loc[bcn_stops["District.Name"] == "Poblenou", 'Transport']

Series([], Name: Transport, dtype: object)

In [77]:
#Create a function to stablish a name indicating the district
def district(row):
    if row["nom_cabina"]=="Palau Reial":
        return "Les corts"
    if row["nom_cabina"]=="Sants":
        return "Sants-Montjuïc"
    if row["nom_cabina"]=="Poblenou":
        return "Sant Martí"
    if row["nom_cabina"]=="Observ Fabra":
        return "Sarrià-Sant Gervasi"
    if row["nom_cabina"]=="Eixample":
        return "Eixample"
    if row["nom_cabina"]=="Gràcia":
        return "Gràcia"

In [78]:
pollution1["District"]= pollution1.apply(district, axis=1)

In [79]:
pollution1.head()

,nom_cabina,qualitat_aire,valor_o3,valor_no2,valor_pm10,generat,District
0,Sants,--,NaN,--,NaN,11/06/2018 9:00,Sants-Montjuïc
1,Eixample,Bona,37,62,26,11/06/2018 9:00,Eixample
2,Gràcia,Bona,51,44,23,11/06/2018 9:00,Gràcia
3,Ciutadella,Bona,27,40,NaN,11/06/2018 9:00,None
4,Vall Hebron,Bona,22,54,18,11/06/2018 9:00,None

In [80]:
pollution1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35983 entries, 0 to 5847
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nom_cabina     35983 non-null  object
 1   qualitat_aire  35983 non-null  object
 2   valor_o3       25157 non-null  object
 3   valor_no2      34113 non-null  object
 4   valor_pm10     21311 non-null  object
 5   generat        35983 non-null  object
 6   District       26819 non-null  object
dtypes: object(7)
memory usage: 1.2+ MB

In [81]:
pollution1.District = pollution1.District.fillna("")

pollution_districts = pollution1[pollution1.District != ""]

In [82]:
pollution_districts.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26819 entries, 0 to 5847
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nom_cabina     26819 non-null  object
 1   qualitat_aire  26819 non-null  object
 2   valor_o3       16310 non-null  object
 3   valor_no2      25258 non-null  object
 4   valor_pm10     17168 non-null  object
 5   generat        26819 non-null  object
 6   District       26819 non-null  object
dtypes: object(7)
memory usage: 942.9+ KB

In [83]:
pollution_districts.valor_no2 = pollution_districts.valor_no2.fillna("")
pollution_districts.valor_no2 = pollution_districts.valor_no2.str.replace("--", "")
pollution_districts.valor_o3 = pollution_districts.valor_o3.fillna("")
pollution_districts.valor_o3 = pollution_districts.valor_o3.str.replace("--", "")
pollution_districts.valor_pm10 = pollution_districts.valor_pm10.fillna("")
pollution_districts.valor_pm10 = pollution_districts.valor_pm10.str.replace("--", "")

C:\Users\ppaau\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [84]:
districts_o3=pollution_districts.loc[pollution_districts["valor_o3"]!="", ["District", "valor_o3"]]
districts_o3.reset_index
districts_no2=pollution_districts.loc[pollution_districts["valor_no2"]!="", ["District", "valor_no2"]]
districts_no2.reset_index
districts_pm10=pollution_districts.loc[pollution_districts["valor_pm10"]!="", ["District", "valor_pm10"]]
districts_pm10.reset_index

<bound method DataFrame.reset_index of                  District valor_pm10
1                Eixample         26
2                  Gràcia         23
5               Les corts         20
6              Sant Martí         21
8                Eixample         27
...                   ...        ...
5841             Eixample         35
5842               Gràcia         37
5845            Les corts         15
5846           Sant Martí         34
5847  Sarrià-Sant Gervasi          7

[16748 rows x 2 columns]>

In [85]:
def only_digits(x):
    if x.isdigit():
        return int(x)
    else:
        return np.NaN

In [86]:
districts_pm10["valor_pm10"] = districts_pm10["valor_pm10"].apply(only_digits)

In [87]:
districts_o3["valor_o3"] = districts_o3["valor_o3"].apply(only_digits)
districts_no2["valor_no2"] = districts_no2["valor_no2"].apply(only_digits)

In [90]:
grouped_districts_pm10=districts_pm10.groupby("District")["valor_pm10"].mean()
grouped_districts_o3=districts_o3.groupby("District")["valor_o3"].mean()
grouped_districts_no2=districts_no2.groupby("District")["valor_no2"].mean()
print(grouped_districts_no2)
print(grouped_districts_o3)
print(grouped_districts_pm10)

District
Eixample               53.267725
Gràcia                 45.206274
Les corts              27.287249
Sant Martí             36.431916
Sants-Montjuïc         31.990743
Sarrià-Sant Gervasi    10.746835
Name: valor_no2, dtype: float64
District
Eixample               33.680225
Gràcia                 41.939024
Les corts              45.399595
Sant Martí             16.000000
Sants-Montjuïc               NaN
Sarrià-Sant Gervasi    76.632245
Name: valor_o3, dtype: float64
District
Eixample               27.207957
Gràcia                 24.767865
Les corts              18.481685
Sant Martí             25.139436
Sants-Montjuïc               NaN
Sarrià-Sant Gervasi    11.867176
Name: valor_pm10, dtype: float64

In [118]:
district_names=bcn_stops["District.Name"].unique()
#distric_names=district_names.to_numpy()
#district_names=pd.Series(district_names)
print(type(district_names))
grouped_stops=bcn_stops.groupby("District.Name")["District.Name"].count()
grouped_stop=grouped_stops.to_numpy()
print((type(grouped_stop)))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [121]:
stops_per_district=pd.DataFrame({"district":district_names, "stops":grouped_stop}, columns=["district", "stops"])
stops_per_district

              district  stops
0  Sarrià-Sant Gervasi    194
1           Nou Barris    525
2             Eixample    227
3       Horta-Guinardó    420
4       Sants-Montjuïc    231
5           Sant Martí    369
6            Les Corts    268
7          Sant Andreu    426
8               Gràcia    468
9         Ciutat Vella    505

In [140]:
mean_pm10_district= pd.DataFrame(districts_pm10.groupby("District")["valor_pm10"].mean())
mean_pm10_district["index"]=[0,1,2,3,4,5]
mean_pm10_district.set_index("index")
mean_pm10_district["district"]=["Eixample", "Gràcia", "Les Corts", "Sant Martí", "Sants-Montjuïc", "Sarrià-Sant Gervasi"]
mean_pm10_district=mean_pm10_district[["district","valor_pm10", "index"]]
mean_pm10_district.set_index("index")

                  district  valor_pm10
index
0                 Eixample   27.207957
1                   Gràcia   24.767865
2                Les Corts   18.481685
3               Sant Martí   25.139436
4           Sants-Montjuïc         NaN
5      Sarrià-Sant Gervasi   11.867176

In [142]:
mean_o3_district= pd.DataFrame(districts_o3.groupby("District")["valor_o3"].mean())
mean_o3_district["index"]=[0,1,2,3,4,5]
mean_o3_district["district"]=["Eixample", "Gràcia", "Les Corts", "Sant Martí", "Sants-Montjuïc", "Sarrià-Sant Gervasi"]
mean_o3_district=mean_o3_district[["district","valor_o3", "index"]]
mean_o3_district.set_index("index")

                  district   valor_o3
index
0                 Eixample  33.680225
1                   Gràcia  41.939024
2                Les Corts  45.399595
3               Sant Martí  16.000000
4           Sants-Montjuïc        NaN
5      Sarrià-Sant Gervasi  76.632245

In [143]:
mean_no2_district= pd.DataFrame(districts_no2.groupby("District")["valor_no2"].mean())
mean_no2_district["index"]=[0,1,2,3,4,5]
mean_no2_district["district"]=["Eixample", "Gràcia", "Les Corts", "Sant Martí", "Sants-Montjuïc", "Sarrià-Sant Gervasi"]
mean_no2_district=mean_no2_district[["district","valor_no2", "index"]]
mean_no2_district.set_index("index")

                  district  valor_no2
index
0                 Eixample  53.267725
1                   Gràcia  45.206274
2                Les Corts  27.287249
3               Sant Martí  36.431916
4           Sants-Montjuïc  31.990743
5      Sarrià-Sant Gervasi  10.746835

In [151]:
final_database=pd.merge(mean_no2_district, mean_o3_district, how="inner", on="district")
final_database=final_database[["district", "valor_no2", "valor_o3"]]
final_database=pd.merge(final_database, mean_pm10_district, how="inner", on="district")
final_database=final_database[["district", "valor_no2", "valor_o3", "valor_pm10"]]
final_database=pd.merge(final_database, stops_per_district, how="inner", on="district")
final_database

              district  valor_no2   valor_o3  valor_pm10  stops
0             Eixample  53.267725  33.680225   27.207957    227
1               Gràcia  45.206274  41.939024   24.767865    468
2            Les Corts  27.287249  45.399595   18.481685    268
3           Sant Martí  36.431916  16.000000   25.139436    369
4       Sants-Montjuïc  31.990743        NaN         NaN    231
5  Sarrià-Sant Gervasi  10.746835  76.632245   11.867176    194

In [153]:
final_database.corr()

            valor_no2  valor_o3  valor_pm10     stops
valor_no2    1.000000 -0.723711    0.963397  0.447413
valor_o3    -0.723711  1.000000   -0.873938 -0.503276
valor_pm10   0.963397 -0.873938    1.000000  0.531125
stops        0.447413 -0.503276    0.531125  1.000000

In [98]:
print(grouped_stops)
print(grouped_districts_o3)

District.Name
Ciutat Vella           194
Eixample               525
Gràcia                 227
Horta-Guinardó         420
Les Corts              231
Nou Barris             369
Sant Andreu            268
Sant Martí             426
Sants-Montjuïc         468
Sarrià-Sant Gervasi    505
Name: District.Name, dtype: int64
District
Eixample               33.680225
Gràcia                 41.939024
Les corts              45.399595
Sant Martí             16.000000
Sants-Montjuïc               NaN
Sarrià-Sant Gervasi    76.632245
Name: valor_o3, dtype: float64

525

In [ ]:
#The Nou Barris and Sant Andreu Districts don't have an air station. Drop them from our analysis.
#The Ciutadella Air Stations doesn't have a district or neighboorhod. Drop it from Air Stations.

In [ ]:
#Next steps
#Find outliers in the Pollution Data Set by neighborhoods
#Drop the outliers
#Calculate the average for each of the neighborhoods
#Calculate std deviation 
#Calculate correlation
#Compare it to the neighborhoods by number of stops. 
#Analyze data